/*
Deployment script for QCTestDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "QCTestDB"
:setvar DefaultFilePrefix "QCTestDB"
:setvar DefaultDataPath "C:\Users\wilcob.SAGEVIP\AppData\Local\Microsoft\VisualStudio\SSDT\QCTestDB\"
:setvar DefaultLogPath "C:\Users\wilcob.SAGEVIP\AppData\Local\Microsoft\VisualStudio\SSDT\QCTestDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
/*
The column [Shopping].[Cart].[CartCode] on table [Shopping].[Cart] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [Shopping].[Cart])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [Shopping].[Wishlist].[ListName] is being dropped, data loss could occur.

The column [Shopping].[Wishlist].[WishlistCode] on table [Shopping].[Wishlist] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [Shopping].[Wishlist].[WishlistName] on table [Shopping].[Wishlist] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [Shopping].[Wishlist])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping DF_Cart_Status...';


GO
ALTER TABLE [Shopping].[Cart] DROP CONSTRAINT [DF_Cart_Status];


GO
PRINT N'Dropping FK_CartOrderRel_Cart...';


GO
ALTER TABLE [Shopping].[CartOrderRel] DROP CONSTRAINT [FK_CartOrderRel_Cart];


GO
PRINT N'Dropping FK_Cart_User...';


GO
ALTER TABLE [Shopping].[Cart] DROP CONSTRAINT [FK_Cart_User];


GO
PRINT N'Dropping FK_Wishlist_User...';


GO
ALTER TABLE [Shopping].[Wishlist] DROP CONSTRAINT [FK_Wishlist_User];


GO
PRINT N'Dropping FK_Wishlist_Item...';


GO
ALTER TABLE [Shopping].[Wishlist] DROP CONSTRAINT [FK_Wishlist_Item];


GO
PRINT N'Dropping FK_Wishlist_Category...';


GO
ALTER TABLE [Shopping].[Wishlist] DROP CONSTRAINT [FK_Wishlist_Category];


GO
PRINT N'Starting rebuilding table [Shopping].[Cart]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Shopping].[tmp_ms_xx_Cart] (
    [CartID]       INT             IDENTITY (1, 1) NOT NULL,
    [UserID]       INT             NOT NULL,
    [CartCode]     VARCHAR (10)    NOT NULL,
    [CreationDate] SMALLDATETIME   NOT NULL,
    [CartTotal]    DECIMAL (18, 2) NOT NULL,
    [ItemCount]    INT             NOT NULL,
    [Status]       VARCHAR (1)     CONSTRAINT [DF_Cart_Status] DEFAULT ('N') NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Cart] PRIMARY KEY CLUSTERED ([CartID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UK_Cart_CartCode] UNIQUE NONCLUSTERED ([CartCode] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Shopping].[Cart])
    BEGIN
        SET IDENTITY_INSERT [Shopping].[tmp_ms_xx_Cart] ON;
        INSERT INTO [Shopping].[tmp_ms_xx_Cart] ([CartID], [UserID], [CreationDate], [CartTotal], [ItemCount], [Status])
        SELECT   [CartID],
                 [UserID],
                 [CreationDate],
                 [CartTotal],
                 [ItemCount],
                 [Status]
        FROM     [Shopping].[Cart]
        ORDER BY [CartID] ASC;
        SET IDENTITY_INSERT [Shopping].[tmp_ms_xx_Cart] OFF;
    END

DROP TABLE [Shopping].[Cart];

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_Cart]', N'Cart';

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_constraint_PK_Cart]', N'PK_Cart', N'OBJECT';

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_constraint_UK_Cart_CartCode]', N'UK_Cart_CartCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Starting rebuilding table [Shopping].[Wishlist]...';


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER OFF;


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Shopping].[tmp_ms_xx_Wishlist] (
    [WishlistID]   INT           IDENTITY (1, 1) NOT NULL,
    [UserID]       INT           NOT NULL,
    [ItemID]       INT           NOT NULL,
    [WishlistCode] VARCHAR (10)  NOT NULL,
    [DateAdded]    SMALLDATETIME NOT NULL,
    [WishlistName] VARCHAR (30)  NOT NULL,
    [CategoryID]   INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Wishlist] PRIMARY KEY CLUSTERED ([WishlistID] ASC),
    CONSTRAINT [tmp_ms_xx_constraint_UK_Whislist_WishlistCode] UNIQUE NONCLUSTERED ([WishlistCode] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Shopping].[Wishlist])
    BEGIN
        SET IDENTITY_INSERT [Shopping].[tmp_ms_xx_Wishlist] ON;
        INSERT INTO [Shopping].[tmp_ms_xx_Wishlist] ([WishlistID], [UserID], [ItemID], [DateAdded], [CategoryID])
        SELECT   [WishlistID],
                 [UserID],
                 [ItemID],
                 [DateAdded],
                 [CategoryID]
        FROM     [Shopping].[Wishlist]
        ORDER BY [WishlistID] ASC;
        SET IDENTITY_INSERT [Shopping].[tmp_ms_xx_Wishlist] OFF;
    END

DROP TABLE [Shopping].[Wishlist];

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_Wishlist]', N'Wishlist';

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_constraint_PK_Wishlist]', N'PK_Wishlist', N'OBJECT';

EXECUTE sp_rename N'[Shopping].[tmp_ms_xx_constraint_UK_Whislist_WishlistCode]', N'UK_Whislist_WishlistCode', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;


GO
PRINT N'Creating UK_User_UserCode...';


GO
ALTER TABLE [Security].[User]
    ADD CONSTRAINT [UK_User_UserCode] UNIQUE NONCLUSTERED ([UserCode] ASC);


GO
PRINT N'Creating UK_Category_CategoryCode...';


GO
ALTER TABLE [Shopping].[Category]
    ADD CONSTRAINT [UK_Category_CategoryCode] UNIQUE NONCLUSTERED ([CategoryCode] ASC);


GO
PRINT N'Creating UK_Item_ItemCode...';


GO
ALTER TABLE [Shopping].[Item]
    ADD CONSTRAINT [UK_Item_ItemCode] UNIQUE NONCLUSTERED ([ItemCode] ASC);


GO
PRINT N'Creating FK_CartOrderRel_Cart...';


GO
ALTER TABLE [Shopping].[CartOrderRel] WITH NOCHECK
    ADD CONSTRAINT [FK_CartOrderRel_Cart] FOREIGN KEY ([CartID]) REFERENCES [Shopping].[Cart] ([CartID]);


GO
PRINT N'Creating FK_Cart_User...';


GO
ALTER TABLE [Shopping].[Cart] WITH NOCHECK
    ADD CONSTRAINT [FK_Cart_User] FOREIGN KEY ([UserID]) REFERENCES [Security].[User] ([UserID]);


GO
PRINT N'Creating FK_Wishlist_User...';


GO
ALTER TABLE [Shopping].[Wishlist] WITH NOCHECK
    ADD CONSTRAINT [FK_Wishlist_User] FOREIGN KEY ([UserID]) REFERENCES [Security].[User] ([UserID]);


GO
PRINT N'Creating FK_Wishlist_Item...';


GO
ALTER TABLE [Shopping].[Wishlist] WITH NOCHECK
    ADD CONSTRAINT [FK_Wishlist_Item] FOREIGN KEY ([ItemID]) REFERENCES [Shopping].[Item] ([ItemID]);


GO
PRINT N'Creating FK_Wishlist_Category...';


GO
ALTER TABLE [Shopping].[Wishlist] WITH NOCHECK
    ADD CONSTRAINT [FK_Wishlist_Category] FOREIGN KEY ([CategoryID]) REFERENCES [Shopping].[Category] ([CategoryID]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [Shopping].[CartOrderRel] WITH CHECK CHECK CONSTRAINT [FK_CartOrderRel_Cart];

ALTER TABLE [Shopping].[Cart] WITH CHECK CHECK CONSTRAINT [FK_Cart_User];

ALTER TABLE [Shopping].[Wishlist] WITH CHECK CHECK CONSTRAINT [FK_Wishlist_User];

ALTER TABLE [Shopping].[Wishlist] WITH CHECK CHECK CONSTRAINT [FK_Wishlist_Item];

ALTER TABLE [Shopping].[Wishlist] WITH CHECK CHECK CONSTRAINT [FK_Wishlist_Category];


GO
PRINT N'Update complete.';


GO
